### ISSUE TITLE
Swipe event props

### ISSUE THREAD

**Issue by MatteoGioioso** [sanfilippopablo/react-swipeable-routes#12]
Hello

Is it possible to access the swipe events?

`onSwiping, onSwipingRight, onSwipingLeft`

Thanks

**Comment by sanfilippopablo** [comment]
Are those real `SwipeableViews` props? I can't find them here: https://react-swipeable-views.com/api/api/

**Comment by MatteoGioioso** [comment]
Sorry, I presumed that `SwipeableViews`, had something similar, but yea, I just need to know if I could access the events from `SwipeableViews`.

Thanks

**Comment by sanfilippopablo** [comment]
Yes. Just pass props to `SwipeableRoutes` and the will be passed down to `SwipeableViews`.

**Comment by MatteoGioioso** [comment]
Alright then! Sorry, I did not notice it in the docs.

Thanks
