### ISSUE TITLE
React Router Redux integration with swipeable-routes

### ISSUE THREAD

**Issue by muhammadbinnaeem** [sanfilippopablo/react-swipeable-routes#14]
I am using react-router-dom with react-router-redux & history. 
history.push route reflect in redux but using  react-swipeable-routes, route change does not reflect in redux. 
`import { syncHistoryWithStore } from 'react-router-redux';`
`const synchistory = syncHistoryWithStore(history, store);`
`<Router history={synchistory}>
      <App />
    </Router>
`

**Comment by sanfilippopablo** [comment]
Hi! Could you make a codesandbox reproducing the problem? You can use this as a template: https://codesandbox.io/s/mj28rq2l18

**Comment by muhammadbinnaeem** [comment]
Sorry it was my mistake. I was using two router tags due to which history attribute was overwritten by other router tag.
