### ISSUE TITLE
preserve query params in url

### ISSUE THREAD

**Issue by RufusK** [sanfilippopablo/react-swipeable-routes#15]
From a tab with url example.com/company?auth=whatever i want to switch to another tab while preserving the query params (for example example.com/user?auth=whatever)

i tried to use defaultParams in Route but as I'm using typescript i get a type error because the Route Component doesnt have this prop

how can I solve this issue?

**Comment by sanfilippopablo** [comment]
Old issue, closing. Reopen if still relevant.
