### ISSUE TITLE
How to do a 404 route or fallback route, and how to combine with a more global router with other routes ?

### ISSUE THREAD

**Issue by HadrienPierart** [sanfilippopablo/react-swipeable-routes#16]
Very neat component by the way, thx a lot !

**Comment by sanfilippopablo** [comment]
Hello! Currently, there's no way to specify a fallback route. It'd be a nice feature to have, so I'll leave this issue open. When none of the routes matches, `SwipeableRoutes` will render the first view.

About how to use it with other routers, there's nothing special. I'll leave you a codesandbox with two examples: using a normal route inside a swipeable route and having swipeable routes inside a normal route:
https://codesandbox.io/s/5z8614kq0n

**Comment by HadrienPierart** [comment]
Hi,

Thanks for the detailled answer.

Indeed, I managed to do something similar, but I still dont see  from your sandbox how to have coexisting routes, some in a swipeable and others not.

However, I just saw that the last version of React Router will allow passing in an array of routes for a given route, which should simplify things a lot to get both working together !
I'll add a code block when I get it working !

**Comment by sanfilippopablo** [comment]
Is this more inline with what you want? Here `Red` and `Blue` are not swipeable and work as normal routes, but the others are swipeable.

https://codesandbox.io/s/zwvokn7jyx

**Comment by HadrienPierart** [comment]
Yes but my router is a bit more complicated than that. Plus, this is entirely solved by https://github.com/sanfilippopablo/react-swipeable-routes/issues/17 and the possibility to use react router v5 and an array of paths on a single route. See my code sample on the other issue.

**Comment by sanfilippopablo** [comment]
Closing this issue. Reopen if still relevant.
