### ISSUE TITLE
Update react dependency

### ISSUE THREAD

**Issue by santialbo** [sanfilippopablo/react-swipeable-routes#2]
Hi could you update the react versions in the package.json to something like
```
  "peerDependencies": {
    "react": "^15.3.0 || ^16.0.0",
    "react-router": "^4.0.0"
  },
```
It's causing me some trouble using react v16.

Thanks for the great work and for opensourcing it :)

**Comment by sanfilippopablo** [comment]
Hi! Thanks for reporting! If I find the time today I will do it. Otherwise you're welcome to send a PR. :slightly_smiling_face:
