### ISSUE TITLE
update to latest version of react-swipeable-views

### ISSUE THREAD

**Issue by mityaustinov** [sanfilippopablo/react-swipeable-routes#23]
Current version of react-swipeable-views is _0.13.9_ and it includes some useful features that are not yet supported in react-swipeable-routes.  Currently routes plugin relies on version _0.12.4_ of swipe plugin.
Would it be possible to update dependencies of the utility? Thank you!

**Comment by sanfilippopablo** [comment]
Fixed in 0.7.0, just released.
