### ISSUE TITLE
Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by arjJha1997** [sanfilippopablo/react-swipeable-routes#31]
```
  140 |   matchedIndex = index;
  141 | } else {
  142 |   React.Children.forEach(children, function (element, index) {
> 143 |     var _element$props2 = element.props,
      | ^  144 |         pathProp = _element$props2.path,
  145 |         exact = _element$props2.exact,
  146 |         strict = _element$props2.strict,
```

**Comment by taniskjha** [comment]
![Screenshot from 2021-04-02 23-28-37](https://user-images.githubusercontent.com/54271649/113441089-42ba7880-940b-11eb-9a4e-8b71f28b56bf.png)

**Comment by taniskjha** [comment]
![Uploading Screenshot from 2021-04-02 23-29-56.png…]()

**Comment by taniskjha** [comment]
![Screenshot from 2021-04-02 23-29-56](https://user-images.githubusercontent.com/54271649/113441182-74334400-940b-11eb-8b86-73a9dca639da.png)
