### ISSUE TITLE
Routes do not get rendered initially

### ISSUE THREAD

**Issue by Benjamin-K** [sanfilippopablo/react-swipeable-routes#7]
## Description

When using your components on nested Routes, only the current (most of the time the first) Route is loaded. The third Route can only be shown **after** the second was also visited, because otherwise there are only two `<div>`s / Routes loaded (instead of three or more).

```jsx
<Router>
  <Route  
      path="/sth"
      render={
        ({ match: { url, params } }) => (
          <SwipeableRoutes animateHeight>
            <Route path={`${url}`} render={ComponentA} />
            <Route path={`${url}/second-path`} component={ComponentB} />
            <Route path={`${url}/third-path`} component={ComponentC} />
          </SwipeableRoutes>
        )
      }
  />
</Router>
```

## Expected behaviour

All routes are rendered, even if they are nested inside another route.

## Current behaviour

Only the first route or routes that have already matched are rendered.

## Steps to reproduce

Use the example from the description above.

**Comment by sanfilippopablo** [comment]
Hi! I couldn't reproduce.
https://codesandbox.io/s/931r1zr6w here it's rendering all routes
